apiVersion: v1
kind: ConfigMap
metadata:
  name: downloadjob-config
  namespace: polyaxon
data:
  run.sh: |-
    cd /data/common-voice
    wget https://voice-prod-bundler-ee1969a6ce8178826482b88e843c335139bd3fb4.s3.amazonaws.com/cv-corpus-1/en.tar.gz  --no-check-certificate