apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: downloader
        image: mwendler/wget
        tag: latest
{{ if .Values.Debug}}
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
{{ else }}
        command: ["/bin/sh"]
        args: ["/etc/config/run.sh"]
{{ end }}
        volumeMounts:
        - name: data
          mountPath: {{ .Values.Download.DestionationPath }}
        - name: config-volume
          mountPath: /etc/config
      restartPolicy: OnFailure
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.Persistence.ClameName}}
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-configmap
            defaultMode: 0744